### ISSUE TITLE
[Request] C# Wrapper

### ISSUE THREAD

**Issue by FZFalzar** [SeriousCache/UABE#101]
Hi, I would like to request a C# Wrapper for UABE API as in its current state it is quite difficult to "guess" the PInvoke and Marshal signatures required

**Comment by DerPopo** [comment]
The caller of some API functions needs to support some C++-specific stuff like std::vector and sometimes needs to be able to call vtable functions. Since it's a C++-API, the names also are mangled.
There's a tool that can automatically create C# wrappers for C++ APIs, I'll see if it can be used in this case.
For now, the best option is creating a custom C++ wrapper for the required functionality that exports its functions with an exports.def file or with `extern "C" __declspec(dllexport)`.
