### ISSUE TITLE
Export to .fbx feature?

### ISSUE THREAD

**Issue by MisterPrawn** [SeriousCache/UABE#123]
I know UABE can export to obj, but it would also be nice to have an option to export as a skinned and weighted fbx file too. Unity Studio can do that as well, but it's old and outdated and as the result, it won't do so with newer games powered by Unity, such as Yooka-Laylee..

If at all possible, I'd like to see a feature to this tool to include .fbx export in the near future. Thank you.

**Comment by bsimser** [comment]
I would be interested in doing this but the project isn't open sourced. Another one (Unity Studio) already supports FBX so you could get full fidelity here. The problem is that product doesn't support the new assets format introduced with Unity 5.2. I'm willing to marry these two functions up but I need some help.
