### ISSUE TITLE
How do I get a Linux build?

### ISSUE THREAD

**Issue by KingDuckZ** [SeriousCache/UABE#193]
I followed the link in the forum to github but I can't see any source, just some readme files.
I'm interested in a Linux build, how can I get one?

**Comment by DerPopo** [comment]
Since there is no linux build, your best bet is using Wine. Since UABE doesn't use any uncommon WinAPI functions, I suspect that it shouldn't be a problem.

I definitely want to create a linux build in the future but it will take lots of work, especially because I will have to create a proper CLI first.

**Comment by happysmash27** [comment]
Could you maybe provide the source code? Maybe others could help port it over.

**Comment by sankasan** [comment]
I just tried this package with `wine-6.12 (Staging)` and although everything seems to work the saved `.uasset` file was classified as corrupted by the Unity Standalone Player. The same steps on Windows did produce a valid `.uasset` file.
