### ISSUE TITLE
Textasset conversion issue?

### ISSUE THREAD

**Issue by carpedee** [SeriousCache/UABE#203]
When I try to convert a textasset file (Unity 5) using the txt plugin (no matter the UABE version) I get something which doesn't appear to be a txt file.

I joined the original dump file and the converted version.
I don't know if it's an issue with the conversion or if the original file is not plain text to begin with? The original file seems to bear the extension ".dcm_ex.pbl.bytes"

[converted.txt](https://github.com/DerPopo/UABE/files/1960332/converted.txt)
[dump.txt](https://github.com/DerPopo/UABE/files/1960333/dump.txt)

Thanks for your help

**Comment by jack980517** [comment]
`.bytes` typically means it's not a plain text file, and the file itself does look like a typical binary file.
I'd say (though I can't be 100% sure) that UABE is doing its job correctly. Just because it's labeled TextAsset doesn't mean it's really plain text.

**Comment by DerPopo** [comment]
The dump stops the string at the first 00 byte of the binary file, but since the TextAsset plugin seems to do it properly, I don't think it is a high priority issue (since strings usually should not contain binary data).

The file definitely is binary, and I don't know which file format that is. Assembly-CSharp.dll should contain hints on what it is (use tools such as dnSpy).
