### ISSUE TITLE
Type database writing code

### ISSUE THREAD

**Issue by 0x900x90** [SeriousCache/UABE#262]
Can you please provide type database writing code? I have an injector and types dumping code. But i don't know how to write types into type database dat file. Sometimes i need to change values in globalgamemanagers. UABE often can't read/write serialized data from it.

**Comment by DerPopo** [comment]
The class database format is still the same as in 2.2 beta3, which has an API release. ClassDatabaseFile.h is the header you're looking for. 
I should definitely get the new API out, though (and add more documentation). As always, you'll probably need to use Visual C++ 2010 in Release mode because of the incompatibilities between standard library versions.

For ClassDatabaseFileStrings, you'll probably want to use GetString instead of directly accessing the fields. To change the string pointer, set fromStringTable to false first. 
The only relevant flag of flags2 is 0x4000 (4 byte alignment).
Feel free to ask any questions if you don't understand something, as it is not documented properly.

**Comment by 0x900x90** [comment]
Completely forgot about API. I'll check it.
