### ISSUE TITLE
Model import

### ISSUE THREAD

**Issue by notpol** [SeriousCache/UABE#287]
Info on usage is sparse as far as i can tell, how do you import models to an assets file for mod creation?

**Comment by DerPopo** [comment]
This is not supported through plugins at the moment.

The only thing you can do is create a Unity project (same Unity version as the game, the version can be found in output_log files, as well as in .assets and bundle files via a hex editor) with your model, build it and use raw/dump export on the relevant assets. 
If you simply want to replace a Mesh (with compatible skeleton), a simple import on the .assets file you want to modify should be enough. Otherwise, you may need to add and manually import a bunch of assets (such as GameObject, Avatar, Mesh, etc) and fix all path IDs inside the assets (through dump export/import). If your assets need a "file path", you may also need to modify the ResourceManager or AssetBundle asset.

I plan to add an option to import object trees in the future, since this is quite a hassle.

**Comment by libYo** [comment]
> I plan to add an option to import object trees in the future, since this is quite a hassle.

Any update?
