### ISSUE TITLE
Unityfs

### ISSUE THREAD

**Issue by astandarduser** [SeriousCache/UABE#295]
So in the unitycache dir there are thousands of folders with _data and _info. The _data has the unityfs header but all it sees on the inside of every file is a text file intead of image/ model data. Any ideas? https://we.tl/t-vzKYaZzkyL

**Comment by 0x900x90** [comment]
Never heared about encoded/encrypted assets?

**Comment by itchyballsack** [comment]
I am asking if they are encrypted, I am not sure how to tell. Considering UABE has worked fine for everything else I have tried I just assumed they are

**Comment by 0x900x90** [comment]
I'm sure your bundle contains encoded bytes.

**Comment by jack980517** [comment]
The "thousands of folders with _data and _info" is a form of asset bundle delivery supported by Unity. Each _data is a small asset bundle containing one file only. If you know the asset name of what you're looking for, you can `grep` every file (or other similar methods) to find the asset, since the asset name is in the header. If not, you probably need to write a program to extract all asset names into a text file and find what you need from there. AFAIK there's no other way.

**Comment by itchyballsack** [comment]
Thanks I did figure out that is was just broken into many parts, however this one I think is encrypted
