### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by flarn2006** [SeriousCache/UABE#307]
I know you're okay with people making derivative works, since you released it under a license that permits that. And I can't think of any reason you wouldn't want people to see how it works. So have you posted the source code anywhere? Why not upload it here?

**Comment by kbrewer08** [comment]
I would like to know this too. Mainly because the page says "source code", but when downloading the zip there's nothing but readme files in it. A game I play just updated to a newer version of unity, and the assets have changed in a way that breaks my own parsing. So I was looking for an example that would help me to update. Since the binary format is not published, I got my hopes up when the UABE page here on Github said "source".

**Comment by happysmash27** [comment]
I don't feel safe running a free program from someone I don't know without source code. What are they hiding that they must distribute binaries only?

**Comment by happysmash27** [comment]
I don't feel safe running a gratis program from someone I don't know without source code. What are they hiding that they must distribute binaries only?
