### ISSUE TITLE
MonoBehaviour formatting error - Unity 2019 added 3 new Keyframe fields

### ISSUE THREAD

**Issue by Rudolpher** [SeriousCache/UABE#318]
Hello

Firstly thank you for UABE, been using it for many years now.
Guessing this might be a Unity version issue since it started showing up a few months back? 
Editing txt-exports directly started causing crashes a while back in various Unity games. Found a tip to hex-edit raw exports instead and use dump as guide, so since I know pretty close to nothing on the subject and it worked I just kept doing it that way.

However now dump can't even be used in a fair few cases, since UABE adds or jumps a few steps and ends up displaying gibberish values.
When viewing the same MonoBehaviour in newly built AssetStudio it displays 4 pointers as 'truncated', exports dump successfully and values match hex. 

<details>
  <summary>Attachments</summary>  

  [AssetsExport.zip](https://github.com/DerPopo/UABE/files/4145420/AssetsExport.zip) 

  <img src="https://user-images.githubusercontent.com/24588620/73615853-46d2e680-460c-11ea-83b3-9475a6638a67.jpg" alt="drawing" width="200"/> 
  
</details>

**Comment by nesrak1** [comment]
Unity 2019 now has three new fields for Keyframes. TypeTreeGenerator probably needs to be updated.
![AssetBundleExtractor_7XdqfFImsk](https://user-images.githubusercontent.com/12544505/73881971-f1265600-4826-11ea-8ccc-0175f84e22a2.png)
AssetStudio probably shows AnimationCurves as truncated because they're one of the special internal types and not important enough.
