### ISSUE TITLE
Unable to open file in read mode

### ISSUE THREAD

**Issue by Nabil12S** [SeriousCache/UABE#368]
so im trying to open package fil but its say "unable to open file in read mode what dows that mean ? am i doing something wrong?
![image](https://user-images.githubusercontent.com/72492533/95304969-92cadf00-08af-11eb-84e0-5125993c22f7.png)

**Comment by steelmonkey** [comment]
I had the same issue because the target file was in my other hard drive. I had to make the whole file path in hard drive it wanted because it wasn't let me change the target path. I'll drop an image below so you can see what I'm talking about
![image](https://user-images.githubusercontent.com/11012089/95799171-b83d5b80-0ca8-11eb-80f8-7261dfe54059.png)
![image](https://user-images.githubusercontent.com/11012089/95799239-ea4ebd80-0ca8-11eb-94ac-7e5ba8d1084b.png)
 It's not as easy as changing a name/letter. Those files have to exist so I had to make the whole path in my C drive.

**Comment by Zarexel** [comment]
I don't have any other hard drives, and it still says it. I have no idea how to fix it.
