### ISSUE TITLE
v3.x Lost Windows XP support: "The procedure entry point InitOnceComplete could not be located in the dynamic link library KERNEL32.dll."

### ISSUE THREAD

**Issue by Corak667** [SeriousCache/UABE#471]
Hi. Latest build lost Windows XP support.
1. Target os version/subversion "v6.0". Replaced counter to 5.0
Then error message.
2.v3.x Lost Windows XP support: "The procedure entry point InitOnceComplete could not be located in the dynamic link library KERNEL32.dll."
![165091281744_kiss_3kb](https://user-images.githubusercontent.com/7928889/165126552-51cacf5f-c90c-4afc-9a29-359bfe029104.png)
http://coraksoft1.narod.ru/scr/2021-11/165091281744_kiss_3kb.png
Please add at least some func to support XP

**Comment by SeriousCache** [comment]
As per https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist, the last Visual Studio/Visual C++ version compatible with Windows XP is VS 2019 16.7. It may be possible to grab a copy of that somewhere and try to compile it, with the CMakeLists adjusted for C++20 instead of 23.  
It likely won't just compile - for instance, UABE uses some C++20 features that the older VS does not seem to support, notably std::format and std::jthread.
Those two are substitutable (e.g. format by [fmtlib](https://github.com/fmtlib/fmt), std::jthread by some std::thread wrapper), but I really wouldn't like to hold back usage on other modern language features.

**Comment by LukeSaward1** [comment]
Who even uses XP nowadays?

There's gonna be a time where you must upgrade if you want the latest versions of software.

**Comment by SeriousCache** [comment]
Closing this. Windows XP support would just hold the code base back.
