### ISSUE TITLE
UABE 3.0 is malware?

### ISSUE THREAD

**Issue by arcticbonnie** [SeriousCache/UABE#483]
My anti virus says that that UABE 3.0 is a virus heres proof 
![image](https://user-images.githubusercontent.com/77703720/166827982-fcdc51d3-0422-4fac-ac2f-6b0f27f41296.png)

**Comment by mskgroup** [comment]
No! #479

**Comment by SeriousCache** [comment]
Just virus scanners doing their thing. "-gen" is one of the common keywords for automatized detection based on whatever analysis, and it's not uncommon for regular applications to be treated as the ~personified~ applicationified evil.
Closing this, since #479 already covers the problem as @mskgroup noted,
