### ISSUE TITLE
Windows Defender deletes this after download.

### ISSUE THREAD

**Issue by Kaspr02** [SeriousCache/UABE#506]
Windows Defender straight out deletes this file when downloaded. Says it's a Trojan.

**Comment by Nytra** [comment]
Same thing happened to me with the latest release, both 32-bit and 64-bit versions

**Comment by SiofraScript** [comment]
Same thing here. Download is rejected due to "Virus Detected" and windows security labels it a Severe Threat in my protection history.

**Comment by AlexsandroZanella2** [comment]
same here

**Comment by SeriousCache** [comment]
#479

**Comment by juanroman74454811** [comment]
Its also a false positive due to many reasons, 1, It thinks its another saw ransomware or something whatever virus it is, And microsoft UNFAIRLY deletes your UABE, causing you to not mod baldis basics and make you really angry about that,
And 2. Microsoft's Windows Defender SUCKS, It really sucks and i dont want it to be on my PC when i download it on my PC, Because it causes false positives to this program,
Microsoft needs to teach a lesson about this!
