### ISSUE TITLE
AndroidOS/Multiverze file flagged as severe trojan

### ISSUE THREAD

**Issue by BluestoneCoder** [SeriousCache/UABE#561]
Trojan:AndroidOS/Multiverze
what does this file even do?

**Comment by SeriousCache** [comment]
It crashed in analysis sandboxes at some point (.NET version stuff probably), Windows' error reporting sent a crash dump to Microsoft servers, some scanners don't like Microsoft servers (rightfully so), and now every scanner on earth is afraid of touching the application with a ten-foot pole. And since this scanner apparently doesn't have the funds for proper prescription glasses, it just assumes it is an Android application in some parallel universe.

#479
