### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by DerPopo** [SeriousCache/UABE#7]
Add asset extracting/importing functionality to the command-line.

**Comment by 0x900x90** [comment]
Maybe add new file functionality from command line as well? Would be nice.

**Comment by 0x900x90** [comment]
Great idea. Maybe adding new file from commandline as well. Would be nice.

**Comment by chrsmith** [comment]
+1 to this idea. The Unity project I've been trying to extract resources for downloads dozens of compressed asset bundles, each containing dozens of textures. I used to use ata4/disunity, which allowed me to automate things using PowerShell. However, because of [this bug](https://github.com/ata4/disunity/issues/172) ata4/disunity no longer works for my project. UABE works fine though, so nice work!

Since it appears that I can only use UABE to do the resource extraction, and having a command-line interface is critical for dealing with the ~1,000 different resource files, I would _really_ like this feature :smile:.

I am happy to write the code, with unit tests, and send you a pull request for review. If you are interested in taking me up on this offer, you can find my email address on my GitHub profile page. Thanks!

**Comment by anddom03** [comment]
+1 also to this. It's most important feature now for me.

Dealing with many files manually is really painful and time consuming.

**Comment by DerPopo** [comment]
You can export the contents of bundle files (such as .assets and .resource files) with the command line as described in Usage.txt and open multiple .assets at once in the UI.

**Comment by anddom03** [comment]
Hey. Thanks for the quick response!

I was looking at it earlier and it was a bit unclear for me. Lets say we have resource.assets in which there is a texture1 file of type Texture2D.
In order to export this texture I create a batch file first that looks like this:
+FILE path_to_data_files\texture1 
Then I use AssetsBundleExtractor batchexport <batch file path>
After modyfing the texture I reimport it with the same batch but with command:
AssetsBundleExtractor batchimport <batch file path>

Is that correct?
I assume that Texture2D will be extracted but not in png format. Is there a way to extract files to desired format and later reimport them to Unity's format?

**Comment by DerPopo** [comment]
Command line extraction doesn't work for .assets files. You can only batch export the .assets, .resource and .dll files from bundles (most often .unity3d), editing .assets files themselves isn't supported.

The normal user interface can batch extract from .assets files, just select all files to export using click+shift/ctrl+click (don't mix e.g. Texture2D with Mesh, do one type at a time). It can't batch import though.

**Comment by Death111** [comment]
Is it possible to add support for extracting all Meshes as OBJ, all Texture2D as PNG (and more) of a given .assets file by using command line?
Because iny my case I have >20 .assets file in it and I want to extract all meshes and textures from all files into a given folder. Doing this by hand is kind of a slow task to do.

**Comment by DerPopo** [comment]
It's not possible through command line at the moment but you can select multiple .assets file in the open dialog. Then sort by the type and select all Meshes, press Plugins and so on.

**Comment by Death111** [comment]
Oh god. I did not know that I can select multiple -.- I opened them all one by one and exported - took ages. Thanks!

**Comment by alexbestul** [comment]
Is there any chance of getting command line support for "Export Dump?"

I've got a huge library (thousands upon thousands) of asset bundles that I'd like to extract information from in order to build a database of asset properties.  Doing that through the UI simply isn't feasible, even with the ability to multi-select.

Ideally, I'd like to be able to use the command line to do the equivalent of selecting everything in a bundle, clicking 'Export Dump', and writing it all to a specified directly (preferably in JSON format, as is already being discussed in #92).

**Comment by Thuya1980** [comment]
I want to edit the texture2d format with .png file in command line.
Is it possible?
